export const productsMock = [
  {
    id: 1,
    name: "V-Neck Sweater",
    description: "Classic v-neck sweater crafted from soft wool for warmth and style.",
    image: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633",
    price: 69.0,
    ratings: 2.5,
    availability: true,
  },
  {
    id: 2,
    name: "Travel Jewelry Organizer",
    description: "Compact storage for your jewelry while traveling.",
    image: "https://images.unsplash.com/photo-1710552524021-a8dc68c2a8dc",
    price: 29.5,
    ratings: 4.2,
    availability: true,
  },
  {
    id: 3,
    name: "Frozen Acai Purée",
    description: "Unsweetened frozen acai purée for smoothies and bowls.",
    image: "https://images.unsplash.com/photo-1590301157890-4810ed352733",
    price: 6.5,
    ratings: 4.7,
    availability: true,
  },
  {
    id: 4,
    name: "Coconut Macaroons",
    description: "Chewy cookies made with coconut, perfect for sweet cravings.",
    image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35",
    price: 8.0,
    ratings: 4.1,
    availability: false,
  },
  {
    id: 5,
    name: "Hibiscus Herbal Tea",
    description: "Floral and refreshing herbal tea, great hot or iced.",
    image: "https://images.unsplash.com/photo-1557800636-894a64c1696f",
    price: 12.0,
    ratings: 4.3,
    availability: true,
  },
  {
    id: 6,
    name: "Pumpkin Spice Granola",
    description: "Crunchy granola with pumpkin spice flavor.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
    price: 10.5,
    ratings: 4.0,
    availability: true,
  },
  {
    id: 7,
    name: "Cinnamon Sugar Donuts",
    description: "Delicious mini donuts dusted with cinnamon sugar.",
    image: "https://images.unsplash.com/photo-1551024601-bec78aea704b",
    price: 4.25,
    ratings: 4.6,
    availability: true,
  },
  {
    id: 8,
    name: "Mango Chili Salsa",
    description: "A sweet and spicy salsa made with mangoes and a hint of chili, great with chips or grilled chicken.",
    image: "https://images.unsplash.com/photo-1514327605112-b887c0e61c0a",
    price: 7.5,
    ratings: 4.4,
    availability: true,
  },
  {
    id: 9,
    name: "Pet Carrier Backpack",
    description: "Comfortable and breathable backpack for carrying small pets.",
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee",
    price: 54.0,
    ratings: 4.0,
    availability: false,
  },
  {
    id: 10,
    name: "Ultra-Thin Laptop Sleeve",
    description: "Sleek and protective sleeve for laptops and tablets.",
    image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302",
    price: 22.0,
    ratings: 4.2,
    availability: true,
  },
  {
    id: 11,
    name: "Merino Wool Cardigan",
    description: "Lightweight cardigan perfect for layering in any season.",
    image: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633",
    price: 89.0,
    ratings: 4.5,
    availability: true,
  },
  {
    id: 12,
    name: "Leather Jewelry Box",
    description: "Elegant leather box with multiple compartments for organizing jewelry.",
    image: "https://images.unsplash.com/photo-1710552524021-a8dc68c2a8dc",
    price: 45.0,
    ratings: 4.8,
    availability: false,
  },
  {
    id: 13,
    name: "Organic Acai Berry Powder",
    description: "Freeze-dried acai powder for smoothies, bowls, and baking.",
    image: "https://images.unsplash.com/photo-1590301157890-4810ed352733",
    price: 18.5,
    ratings: 4.6,
    availability: true,
  },
  {
    id: 14,
    name: "Chocolate Coconut Bars",
    description: "Decadent chocolate-covered coconut bars for dessert lovers.",
    image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35",
    price: 12.5,
    ratings: 4.9,
    availability: true,
  },
  {
    id: 15,
    name: "Chamomile Lavender Tea",
    description: "Soothing blend of chamomile and lavender for relaxation.",
    image: "https://images.unsplash.com/photo-1557800636-894a64c1696f",
    price: 9.75,
    ratings: 4.4,
    availability: true,
  },
  {
    id: 16,
    name: "Maple Pecan Granola",
    description: "Sweet and nutty granola with real maple syrup and pecans.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
    price: 13.0,
    ratings: 4.7,
    availability: false,
  },
  {
    id: 17,
    name: "Glazed Mini Donuts",
    description: "Bite-sized donuts with a sweet vanilla glaze.",
    image: "https://images.unsplash.com/photo-1551024601-bec78aea704b",
    price: 5.5,
    ratings: 4.3,
    availability: true,
  },
  {
    id: 18,
    name: "Pineapple Habanero Salsa",
    description: "Tropical salsa with a fiery kick from habanero peppers.",
    image: "https://images.unsplash.com/photo-1514327605112-b887c0e61c0a",
    price: 8.25,
    ratings: 4.5,
    availability: true,
  },
  {
    id: 19,
    name: "Collapsible Pet Travel Crate",
    description: "Portable and foldable crate for easy pet transportation.",
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee",
    price: 68.0,
    ratings: 4.1,
    availability: true,
  },
  {
    id: 20,
    name: "Padded Laptop Case",
    description: "Extra cushioned protection for your laptop with multiple pockets.",
    image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302",
    price: 35.0,
    ratings: 4.6,
    availability: true,
  },
  {
    id: 21,
    name: "Cashmere V-Neck Sweater",
    description: "Luxurious cashmere blend sweater with timeless v-neck design.",
    image: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633",
    price: 125.0,
    ratings: 4.9,
    availability: false,
  },
  {
    id: 22,
    name: "Velvet Jewelry Pouch Set",
    description: "Set of 5 soft velvet pouches in assorted colors for jewelry protection.",
    image: "https://images.unsplash.com/photo-1710552524021-a8dc68c2a8dc",
    price: 15.5,
    ratings: 4.0,
    availability: true,
  },
  {
    id: 23,
    name: "Acai Energy Smoothie Mix",
    description: "Ready-to-blend acai mix with superfoods for an energy boost.",
    image: "https://images.unsplash.com/photo-1590301157890-4810ed352733",
    price: 24.0,
    ratings: 4.5,
    availability: true,
  },
  {
    id: 24,
    name: "Almond Coconut Biscotti",
    description: "Crunchy Italian biscotti with coconut and almond flavors.",
    image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35",
    price: 11.0,
    ratings: 4.3,
    availability: true,
  },
  {
    id: 25,
    name: "Mint Green Tea Blend",
    description: "Refreshing green tea infused with natural mint leaves.",
    image: "https://images.unsplash.com/photo-1557800636-894a64c1696f",
    price: 14.5,
    ratings: 4.6,
    availability: false,
  },
  {
    id: 26,
    name: "Dark Chocolate Granola",
    description: "Rich dark chocolate granola clusters with almonds.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
    price: 11.75,
    ratings: 4.8,
    availability: true,
  },
  {
    id: 27,
    name: "Powdered Sugar Donuts",
    description: "Classic donuts generously dusted with powdered sugar.",
    image: "https://images.unsplash.com/photo-1551024601-bec78aea704b",
    price: 4.75,
    ratings: 4.2,
    availability: true,
  },
  {
    id: 28,
    name: "Peach Jalapeño Salsa",
    description: "Sweet peach salsa with a spicy jalapeño twist.",
    image: "https://images.unsplash.com/photo-1514327605112-b887c0e61c0a",
    price: 7.0,
    ratings: 4.7,
    availability: true,
  },
  {
    id: 29,
    name: "Wheeled Pet Carrier",
    description: "Rolling carrier with retractable handle for easy pet transport.",
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee",
    price: 85.0,
    ratings: 4.4,
    availability: true,
  },
  {
    id: 30,
    name: "Hardshell Laptop Case",
    description: "Durable hardshell case with shock-absorbing corners.",
    image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302",
    price: 42.0,
    ratings: 4.5,
    availability: false,
  },
  {
    id: 31,
    name: "Cable Knit Sweater",
    description: "Cozy cable knit design in premium cotton blend.",
    image: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633",
    price: 78.0,
    ratings: 4.1,
    availability: true,
  },
  {
    id: 32,
    name: "Stackable Jewelry Trays",
    description: "Modular tray system for customizable jewelry storage.",
    image: "https://images.unsplash.com/photo-1710552524021-a8dc68c2a8dc",
    price: 38.0,
    ratings: 4.6,
    availability: true,
  },
  {
    id: 33,
    name: "Acai Superfood Capsules",
    description: "Concentrated acai berry extract in convenient capsule form.",
    image: "https://images.unsplash.com/photo-1590301157890-4810ed352733",
    price: 32.0,
    ratings: 4.2,
    availability: true,
  },
  {
    id: 34,
    name: "Coconut Flour Cookies",
    description: "Gluten-free cookies made with coconut flour and natural sweeteners.",
    image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35",
    price: 9.5,
    ratings: 4.4,
    availability: false,
  },
  {
    id: 35,
    name: "Earl Grey Tea Collection",
    description: "Premium Earl Grey varieties with bergamot and citrus notes.",
    image: "https://images.unsplash.com/photo-1557800636-894a64c1696f",
    price: 16.0,
    ratings: 4.7,
    availability: true,
  },
  {
    id: 36,
    name: "Honey Almond Granola",
    description: "Sweet honey-roasted granola with crunchy almonds.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
    price: 12.25,
    ratings: 4.5,
    availability: true,
  },
  {
    id: 37,
    name: "Chocolate Filled Donuts",
    description: "Fluffy donuts filled with rich chocolate cream.",
    image: "https://images.unsplash.com/photo-1551024601-bec78aea704b",
    price: 6.0,
    ratings: 4.8,
    availability: true,
  },
  {
    id: 38,
    name: "Strawberry Basil Salsa",
    description: "Unique fruity salsa combining strawberries and fresh basil.",
    image: "https://images.unsplash.com/photo-1514327605112-b887c0e61c0a",
    price: 8.75,
    ratings: 4.1,
    availability: true,
  },
  {
    id: 39,
    name: "Airline Approved Pet Carrier",
    description: "TSA-compliant soft carrier that fits under airplane seats.",
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee",
    price: 62.0,
    ratings: 4.6,
    availability: false,
  },
  {
    id: 40,
    name: "Waterproof Laptop Sleeve",
    description: "Water-resistant neoprene sleeve with reinforced edges.",
    image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302",
    price: 28.0,
    ratings: 4.3,
    availability: true,
  },
];
